# đ


In [1]:
from paddleocr import PaddleOCR

# Khởi tạo OCR hỗ trợ tiếng Việt
ocr = PaddleOCR(
    lang='vi',                     # Quan trọng: bật tiếng Việt
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False
)

# Ảnh đầu vào
img_path = "doc1.png"

# Nhận dạng chữ
result = ocr.predict(img_path)

for line in result:
    print(line)
    line.save_to_json("output")  # Lưu từng dòng ra file JSON



d:\Study\Projects\HK7\QuichQuiz\venv\Lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:718: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('latin_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\latin_PP-OCRv5_mobile_rec`.


{'input_path': 'doc1.png', 'page_index': None, 'doc_preprocessor_res': {'input_path': None, 'page_index': None, 'input_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8), 'model_settings': {'use_doc_orientation_classify': False, 'use_doc_unwarping': False}, 'angle': -1, 'rot_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8), 'output_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8)}, 'dt_polys': [array([[17, 21],
       ...,
       [17, 46]], shape=(4, 2), dtype=int16), array([[ 18,  87],
       ...,
       [ 18, 109]], shape=(4, 2), dtype=int16), array([[ 18, 124],
       ...,
       [ 18, 145]], shape=(4, 2), dtyp

In [69]:
print(type(result[0]['rec_boxes']))
print(result[0]['rec_boxes'])
print("=== In từng box ===")
for box in result[0]['rec_boxes']:
    for point in box:
        print(point)

<class 'numpy.ndarray'>
[[ 17 ...  46]
 ...
 [ 18 ... 209]]
=== In từng box ===
17
21
158
46
18
87
1021
109
18
124
618
145
18
188
638
209


In [ ]:
paragrap = []
for line in result:  
    for sentence in line['rec_texts']:
        paragrap.append(sentence)
    line.save_to_json("output")
    

for txt in paragrap:
    print(txt)


Căn c Quyt đnh s 2815/QĐ-ĐHSPKT ngày 13/9/2022 ca Hiu
trưng trưng Đi hc Sư phm K thut Tp. HCM v vic ban hành quy
đnh v Công tác Khen thưng và K lut đ vi sinh viên đi hc h chính
quy ca Trưng Đi hc Sư phm K thut Thành ph H Chí Minh; Quyt
đnh s 3289/QĐ-ĐHSPKT ngày 03/11/2022; Quyt đnh s 936/QĐ-
ĐHSPKT ngày 31/3/2023, Quyt đnh s 2192/QĐ-ĐHSPKT ngày
17/7/2023 và Quyt đnh s 468/QĐ-ĐHSPKT ngày 21/02/2024 Vê vic
sa đi b sung mt s đu ca Quy đnh v Công tác Khen thưng và K
lut đi v sinh viên đi hc h chính quy ca Trưng Đi hc Sư phm K
thut Thành ph H Chí Minh;


In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.7.1+cu118
False


In [101]:
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from PIL import Image
import torch
import re

# Load pretrained TrOCR
processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-printed")
model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-printed")

# Mở ảnh
image_path = "doc1.png"
image = Image.open(image_path).convert("RGB")

# OCR
pixel_values = processor(images=image, return_tensors="pt").pixel_values
generated_ids = model.generate(pixel_values)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print("OCR Output:")
print(generated_text)


Some weights of VisionEncoderDecoderModel were not initialized from the model checkpoint at microsoft/trocr-base-printed and are newly initialized: ['encoder.pooler.dense.bias', 'encoder.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


OCR Output:
EXCLUDING ON BACK:


# PaddleOCR + TrOCR

In [ ]:
from paddleocr import PaddleOCR
import numpy as np
from PIL import Image
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
import torch
import re

# ✅ PaddleOCR chỉ dùng để detect bbox
paddleocr = PaddleOCR(lang="vi")

# ✅ Model TrOCR dành cho text in
TROCR_MODEL = "microsoft/trocr-base-printed"
MODEL_PATH = "./quickquiz/Models/checkp"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ✅ Load TrOCR – thêm trust_remote_code nếu version mới
processor = TrOCRProcessor.from_pretrained(
    TROCR_MODEL,
    trust_remote_code=True
)

model = VisionEncoderDecoderModel.from_pretrained(
    MODEL_PATH,
    trust_remote_code=True
).to(device)

print("✅ TrOCR loaded thành công")


Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-LCNet_x1_0_doc_ori`.


Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\UVDoc`.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('latin_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\latin_PP-OCRv5_mobile_rec`.


Device: cpu


OSError: Can't load image processor for './quickquiz/Models/checkp'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './quickquiz/Models/checkp' is the correct path to a directory containing a preprocessor_config.json file

In [5]:
from PIL import Image
import torch
from transformers import TrOCRProcessor, VisionEncoderDecoderModel

device = "cuda" if torch.cuda.is_available() else "cpu"

processor = TrOCRProcessor.from_pretrained(MODEL_PATH)
model = VisionEncoderDecoderModel.from_pretrained(MODEL_PATH).to(device)
model.eval()

# load ảnh thô
image = Image.open("test.jpg").convert("RGB")

# xử lý đúng chuẩn
inputs = processor(images=image, return_tensors="pt").to(device)

with torch.no_grad():
    generated_ids = model.generate(**inputs)

text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
print("Kết quả:", text)


OSError: Can't load image processor for './quickquiz/Models/checkp'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure './quickquiz/Models/checkp' is the correct path to a directory containing a preprocessor_config.json file

In [ ]:
img_path = "trocr.png"
image = Image.open(img_path).convert("RGB")
input = processor(images=image, return_tensors="pt").pixel_values.to(device)
generated_ids = model.generate(input)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]
print("Generated Text:", generated_text)

Generated Text: 


In [2]:

def detect_text_boxes(image_path):
    """
    Nhận đầu vào: path ảnh
    Trả về: list bbox dạng [x1, y1, x2, y2]
    """

    # Chạy detect
    result = paddleocr.predict(image_path)

    bboxes = []

    for box in result[0]['rec_boxes']:
        bboxes.append(box)

    return bboxes




In [3]:
image_path = "doc.png"  # đổi thành file bạn có
bboxes = detect_text_boxes(image_path)

print("Số vùng phát hiện:", len(bboxes))
for b in bboxes:
    print(b)


Số vùng phát hiện: 10
[54 ... 14]
[ 0 ... 43]
[ 0 ... 70]
[ 0 ... 97]
[  0 ... 122]
[  0 ... 149]
[  0 ... 175]
[  0 ... 200]
[  0 ... 227]
[  0 ... 253]


In [4]:
from PIL import Image

def crop_boxes(image_path, bboxes):
    """
    Input:
        image_path: đường dẫn ảnh gốc
        bboxes: list bbox dạng [x1, y1, x2, y2]
    Output:
        list các ảnh crop (PIL.Image)
    """
    img = Image.open(image_path).convert("RGB")
    crops = []

    for (x1, y1, x2, y2) in bboxes:
        crop = img.crop((x1, y1, x2, y2))
        crops.append(crop)

    return crops


In [11]:
crops = crop_boxes(image_path, bboxes)

print("Số ảnh crop:", len(crops))
crops[4].show()   # hiển thị crop dòng đầu


Số ảnh crop: 10


In [8]:
def normalize_case(text):
    text = text.lower()  # toàn bộ lower
    text = re.sub(r'([.!?]\s+)([a-z])', lambda m: m.group(1) + m.group(2).upper(), text)  # viết hoa đầu câu
    if text: text = text[0].upper() + text[1:]
    return text

def trocr_read(image):
    # image: PIL.Image crop
    
    inputs = processor(image, return_tensors="pt").pixel_values.to(device)

    with torch.no_grad():
        generated_ids = model.generate(
            inputs,
            max_new_tokens=256,
            num_beams=4,
            early_stopping=True
        )

    text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    print("=== TrOCR output:", text)
    return normalize_case(text)


In [9]:
texts = [trocr_read(c) for c in crops]

for t in texts:
    print(t)


=== TrOCR output: 
=== TrOCR output: 
=== TrOCR output: 
=== TrOCR output: 
=== TrOCR output: 
=== TrOCR output: 
=== TrOCR output: 


KeyboardInterrupt: 

In [ ]:
paragraph = "\n".join(texts)
print("\n===== OCR Paragraph =====\n")
print(paragraph)



===== OCR Paragraph =====

Cashier
Please with receipt notebook
Thanks condited when the primo well not refund with usen follow bebook
Qty cla triding pai hoc stornam ki thuat thank dh6 h6 chi minn: ovey
Dinh s6 3289/qb-bhspkt nav 03/11/2022; qtyet dinh s6 936/qb-
Bhspkt agay 31/3/2023, quyet dinh s6 2192/qb-bhspkt regay
17/7/2023 va quyet dinh s6 468/qb-bhspkt regay 21/02/2024 ve viec
Sube doi do sing not so diew cua qty dinnive cong tac khen thurong ya ky
Please for non when of recipe chown qty cla invoing be inoc summary
Inual inamn pro ho chi minn,


# Summaries

In [10]:
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback,
)
import torch

from peft import LoraConfig, get_peft_model, TaskType, PeftModel

In [ ]:
# ==== Cấu hình cơ bản ====
BASE_MODEL = "VietAI/vit5-base"
LORA_PATH = "./quickquiz/Models/ViT5_checkpoint_epochs4"

# Seed
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cpu


In [14]:
base_model = AutoModelForSeq2SeqLM.from_pretrained(BASE_MODEL)
model = PeftModel.from_pretrained(base_model, LORA_PATH)
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)
tokenizer.padding_side = "right"


In [26]:
def summarize_text(text):
    """
    Sử dụng model summaries để tóm tắt văn bản.
    Model: mT5, ViT5,...
    """
    inputs = tokenizer(
        f'Tóm tắt: {text}',
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    outputs = model.generate(
        **inputs,
        max_length=250,
        num_beams=5,
        early_stopping=True,
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [32]:
text = '''Docker là một nền tảng phần mềm giúp bạn building, deploying và running ứng dụng dễ dàng hơn bằng cách sử dụng các containers (trên nền tảng ảo hóa).
Docker đóng gói phần mềm thành các container tiêu chuẩn hóa, chứa đựng tất cả những thứ cần thiết để phần mềm hoạt động như thư viện, công cụ hệ thống, mã nguồn và thời gian chạy. Khi cần deploy app lên bất kỳ server nào, bạn chỉ cần run container của Docker thì app của bạn sẽ được khởi chạy ngay lập tức.

Khi sử dụng Docker, bạn có thể dễ dàng triển khai và mở rộng quy mô ứng dụng trong bất kỳ môi trường nào, đồng thời đảm bảo rằng mã nguồn của bạn sẽ luôn chạy được một cách ổn định.
Container là các gói phần mềm nhỏ gọn chứa tất cả các thành phần cần thiết của một ứng dụng như mã nguồn, thư viện, và các công cụ, giúp đảm bảo ứng dụng có thể chạy đồng nhất trên mọi môi trường.

Bằng cách đó, nhờ vào container, ứng dụng sẽ chạy trên mọi máy Linux khác bất kể mọi cài đặt tùy chỉnh mà máy có thể khác với máy được sử dụng để viết code.
'''
print(summarize_text(text))


Docker là một nền tảng phần mềm giúp bạn building, deploying và running ứng dụng dễ dàng hơn bằng cách sử dụng các container tiêu chuẩn hóa. 


# DeepSeek OCR

In [4]:
from transformers import AutoModel, AutoTokenizer
import torch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
model_name = 'deepseek-ai/DeepSeek-OCR'

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModel.from_pretrained(model_name,trust_remote_code=True, use_safetensors=True)
model = model.eval().cuda().to(torch.bfloat16)

# prompt = "<image>\nFree OCR. "
prompt = "<image>\n<|grounding|>Convert the document to markdown. "
image_file = 'doc1.png'
output_path = 'your/output/dir'

res = model.infer(tokenizer, prompt=prompt, image_file=image_file, output_path = output_path, base_size = 1024, image_size = 640, crop_mode=True, save_results = True, test_compress = True)

ImportError: cannot import name 'LlamaFlashAttention2' from 'transformers.models.llama.modeling_llama' (d:\Study\Projects\HK7\QuichQuiz\venv\Lib\site-packages\transformers\models\llama\modeling_llama.py)

# TrOCR prepare data

In [21]:
import os
import random
import shutil

def extract_split(src_root, dst_root, split, ratio):
    print(f"\n===== XỬ LÝ TẬP: {split.upper()} =====")

    src_img_folder = os.path.join(src_root, split, "images")
    src_label_file = os.path.join(src_root, split, "labels.txt")

    dst_split_folder = os.path.join(dst_root, split)
    dst_img_folder = os.path.join(dst_split_folder, "images")
    dst_label_file = os.path.join(dst_split_folder, "labels.txt")

    os.makedirs(dst_img_folder, exist_ok=True)

    # Đọc labels
    with open(src_label_file, "r", encoding="utf-8") as f:
        lines = f.readlines()

    total = len(lines)
    sample_size = max(1, int(total * ratio))

    print(f"Tổng số mẫu: {total}")
    print(f"Tỉ lệ: {ratio*100:.1f}% -> lấy {sample_size}")

    random.seed(42)
    sampled = random.sample(lines, sample_size)

    # Lưu labels nhỏ
    with open(dst_label_file, "w", encoding="utf-8") as f:
        f.writelines(sampled)

    print(f"Đã ghi labels mới vào: {dst_label_file}")

    # Copy ảnh phù hợp
    missing = 0
    copied = 0

    for idx, line in enumerate(sampled):
        # Format: images/xxx.jpg|text...
        left, right = line.split("|", 1)
        img_name = left.strip()

        # Bỏ "images/" ở đầu
        if img_name.startswith("images/"):
            img_name = img_name.replace("images/", "", 1)

        src_img_path = os.path.join(src_img_folder, img_name)
        dst_img_path = os.path.join(dst_img_folder, img_name)

        if not os.path.exists(src_img_path):
            print(f"[CẢNH BÁO] Ảnh không tồn tại: {img_name}")
            missing += 1
            continue

        shutil.copy(src_img_path, dst_img_path)
        copied += 1

        if (idx + 1) % 50 == 0 or idx == sample_size - 1:
            print(f"  + Copy {idx+1}/{sample_size}")

    print("Kết quả:")
    print(f"  - Copy thành công: {copied}")
    print(f"  - Ảnh thiếu: {missing}")
    print(f"  - Labels ghi: {sample_size}")


def extract_all(src_root, dst_root, ratios):
    for split in ["train", "valid", "test"]:
        extract_split(src_root, dst_root, split, ratios.get(split, 0))


# Tỉ lệ do bạn chọn
ratios = {
    "train": 0.03,
    "valid": 0.02,
    "test":  0.1
}

extract_all("data", "data_small", ratios)



===== XỬ LÝ TẬP: TRAIN =====
Tổng số mẫu: 280897
Tỉ lệ: 3.0% -> lấy 8426
Đã ghi labels mới vào: data_small\train\labels.txt
  + Copy 50/8426
  + Copy 100/8426
  + Copy 150/8426
  + Copy 200/8426
  + Copy 250/8426
  + Copy 300/8426
  + Copy 350/8426
  + Copy 400/8426
  + Copy 450/8426
  + Copy 500/8426
  + Copy 550/8426
  + Copy 600/8426
  + Copy 650/8426
  + Copy 700/8426
  + Copy 750/8426
  + Copy 800/8426
  + Copy 850/8426
  + Copy 900/8426
  + Copy 950/8426
  + Copy 1000/8426
  + Copy 1050/8426
  + Copy 1100/8426
  + Copy 1150/8426
  + Copy 1200/8426
  + Copy 1250/8426
  + Copy 1300/8426
  + Copy 1350/8426
  + Copy 1400/8426
  + Copy 1450/8426
  + Copy 1500/8426
  + Copy 1550/8426
  + Copy 1600/8426
  + Copy 1650/8426
  + Copy 1700/8426
  + Copy 1750/8426
  + Copy 1800/8426
  + Copy 1850/8426
  + Copy 1900/8426
  + Copy 1950/8426
  + Copy 2000/8426
  + Copy 2050/8426
  + Copy 2100/8426
  + Copy 2150/8426
  + Copy 2200/8426
  + Copy 2250/8426
  + Copy 2300/8426
  + Copy 2350/8426
  