# đ


In [68]:
from paddleocr import PaddleOCR

# Khởi tạo OCR hỗ trợ tiếng Việt
ocr = PaddleOCR(
    lang='vi',                     # Quan trọng: bật tiếng Việt
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False
)

# Ảnh đầu vào
img_path = "doc1.png"

# Nhận dạng chữ
result = ocr.predict(img_path)

for line in result:
    print(line)
    line.save_to_json("output")  # Lưu từng dòng ra file JSON



Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('latin_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\latin_PP-OCRv5_mobile_rec`.


{'input_path': 'doc1.png', 'page_index': None, 'doc_preprocessor_res': {'input_path': None, 'page_index': None, 'input_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8), 'model_settings': {'use_doc_orientation_classify': False, 'use_doc_unwarping': False}, 'angle': -1, 'rot_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8), 'output_img': array([[[25, ..., 11],
        ...,
        [25, ..., 11]],

       ...,

       [[25, ..., 11],
        ...,
        [25, ..., 11]]], shape=(236, 1052, 3), dtype=uint8)}, 'dt_polys': [array([[17, 21],
       ...,
       [17, 46]], shape=(4, 2), dtype=int16), array([[ 18,  87],
       ...,
       [ 18, 109]], shape=(4, 2), dtype=int16), array([[ 18, 124],
       ...,
       [ 18, 145]], shape=(4, 2), dtyp

In [69]:
print(type(result[0]['rec_boxes']))
print(result[0]['rec_boxes'])
print("=== In từng box ===")
for box in result[0]['rec_boxes']:
    for point in box:
        print(point)

<class 'numpy.ndarray'>
[[ 17 ...  46]
 ...
 [ 18 ... 209]]
=== In từng box ===
17
21
158
46
18
87
1021
109
18
124
618
145
18
188
638
209


In [ ]:
paragrap = []
for line in result:  
    for sentence in line['rec_texts']:
        paragrap.append(sentence)
    line.save_to_json("output")
    

for txt in paragrap:
    print(txt)


Căn c Quyt đnh s 2815/QĐ-ĐHSPKT ngày 13/9/2022 ca Hiu
trưng trưng Đi hc Sư phm K thut Tp. HCM v vic ban hành quy
đnh v Công tác Khen thưng và K lut đ vi sinh viên đi hc h chính
quy ca Trưng Đi hc Sư phm K thut Thành ph H Chí Minh; Quyt
đnh s 3289/QĐ-ĐHSPKT ngày 03/11/2022; Quyt đnh s 936/QĐ-
ĐHSPKT ngày 31/3/2023, Quyt đnh s 2192/QĐ-ĐHSPKT ngày
17/7/2023 và Quyt đnh s 468/QĐ-ĐHSPKT ngày 21/02/2024 Vê vic
sa đi b sung mt s đu ca Quy đnh v Công tác Khen thưng và K
lut đi v sinh viên đi hc h chính quy ca Trưng Đi hc Sư phm K
thut Thành ph H Chí Minh;


In [4]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.7.1+cu118
False


In [101]:
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
from PIL import Image
import torch
import re

# Load pretrained TrOCR
processor = TrOCRProcessor.from_pretrained("microsoft/trocr-base-printed")
model = VisionEncoderDecoderModel.from_pretrained("microsoft/trocr-base-printed")

# Mở ảnh
image_path = "doc1.png"
image = Image.open(image_path).convert("RGB")

# OCR
pixel_values = processor(images=image, return_tensors="pt").pixel_values
generated_ids = model.generate(pixel_values)
generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0]

print("OCR Output:")
print(generated_text)


Some weights of VisionEncoderDecoderModel were not initialized from the model checkpoint at microsoft/trocr-base-printed and are newly initialized: ['encoder.pooler.dense.bias', 'encoder.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


OCR Output:
EXCLUDING ON BACK:


# PaddleOCR + TrOCR

In [ ]:
from paddleocr import PaddleOCR
import numpy as np
from PIL import Image
from transformers import TrOCRProcessor, VisionEncoderDecoderModel
import torch
import re

# ✅ PaddleOCR chỉ dùng để detect bbox
paddleocr = PaddleOCR(lang="vi")

# ✅ Model TrOCR dành cho text in
TROCR_MODEL = "microsoft/trocr-base-printed"

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# ✅ Load TrOCR – thêm trust_remote_code nếu version mới
processor = TrOCRProcessor.from_pretrained(
    TROCR_MODEL,
    trust_remote_code=True
)

model = VisionEncoderDecoderModel.from_pretrained(
    TROCR_MODEL,
    trust_remote_code=True
).to(device)

print("✅ TrOCR loaded thành công")


Creating model: ('PP-LCNet_x1_0_doc_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-LCNet_x1_0_doc_ori`.
Creating model: ('UVDoc', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\UVDoc`.
Creating model: ('PP-LCNet_x1_0_textline_ori', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-LCNet_x1_0_textline_ori`.
Creating model: ('PP-OCRv5_server_det', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddlex\official_models\PP-OCRv5_server_det`.
Creating model: ('latin_PP-OCRv5_mobile_rec', None)
Model files already exist. Using cached files. To redownload, please delete the directory manually: `C:\Users\Admin\.paddl

Device: cpu


Some weights of VisionEncoderDecoderModel were not initialized from the model checkpoint at microsoft/trocr-base-printed and are newly initialized: ['encoder.pooler.dense.bias', 'encoder.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


✅ TrOCR loaded thành công


In [92]:

def detect_text_boxes(image_path):
    """
    Nhận đầu vào: path ảnh
    Trả về: list bbox dạng [x1, y1, x2, y2]
    """

    # Chạy detect
    result = paddleocr.predict(image_path)

    bboxes = []

    for box in result[0]['rec_boxes']:
        bboxes.append(box)

    return bboxes




In [103]:
image_path = "doc.png"  # đổi thành file bạn có
bboxes = detect_text_boxes(image_path)

print("Số vùng phát hiện:", len(bboxes))
for b in bboxes:
    print(b)


Số vùng phát hiện: 10
[54 ... 14]
[ 0 ... 43]
[ 0 ... 70]
[ 0 ... 97]
[  0 ... 122]
[  0 ... 149]
[  0 ... 175]
[  0 ... 200]
[  0 ... 227]
[  0 ... 253]


In [104]:
from PIL import Image

def crop_boxes(image_path, bboxes):
    """
    Input:
        image_path: đường dẫn ảnh gốc
        bboxes: list bbox dạng [x1, y1, x2, y2]
    Output:
        list các ảnh crop (PIL.Image)
    """
    img = Image.open(image_path).convert("RGB")
    crops = []

    for (x1, y1, x2, y2) in bboxes:
        crop = img.crop((x1, y1, x2, y2))
        crops.append(crop)

    return crops


In [105]:
crops = crop_boxes(image_path, bboxes)

print("Số ảnh crop:", len(crops))
crops[0].show()   # hiển thị crop dòng đầu


Số ảnh crop: 10


In [106]:
def normalize_case(text):
    text = text.lower()  # toàn bộ lower
    text = re.sub(r'([.!?]\s+)([a-z])', lambda m: m.group(1) + m.group(2).upper(), text)  # viết hoa đầu câu
    if text: text = text[0].upper() + text[1:]
    return text

def trocr_read(image):
    # image: PIL.Image crop
    
    inputs = processor(image, return_tensors="pt").pixel_values.to(device)

    with torch.no_grad():
        generated_ids = model.generate(
            inputs,
            max_new_tokens=256,
            num_beams=4,
            early_stopping=True
        )

    text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()
    return normalize_case(text)


In [107]:
texts = [trocr_read(c) for c in crops]

for t in texts:
    print(t)


Cashier
Please with receipt notebook
Thanks condited when the primo well not refund with usen follow bebook
Qty cla triding pai hoc stornam ki thuat thank dh6 h6 chi minn: ovey
Dinh s6 3289/qb-bhspkt nav 03/11/2022; qtyet dinh s6 936/qb-
Bhspkt agay 31/3/2023, quyet dinh s6 2192/qb-bhspkt regay
17/7/2023 va quyet dinh s6 468/qb-bhspkt regay 21/02/2024 ve viec
Sube doi do sing not so diew cua qty dinnive cong tac khen thurong ya ky
Please for non when of recipe chown qty cla invoing be inoc summary
Inual inamn pro ho chi minn,


In [108]:
paragraph = "\n".join(texts)
print("\n===== OCR Paragraph =====\n")
print(paragraph)



===== OCR Paragraph =====

Cashier
Please with receipt notebook
Thanks condited when the primo well not refund with usen follow bebook
Qty cla triding pai hoc stornam ki thuat thank dh6 h6 chi minn: ovey
Dinh s6 3289/qb-bhspkt nav 03/11/2022; qtyet dinh s6 936/qb-
Bhspkt agay 31/3/2023, quyet dinh s6 2192/qb-bhspkt regay
17/7/2023 va quyet dinh s6 468/qb-bhspkt regay 21/02/2024 ve viec
Sube doi do sing not so diew cua qty dinnive cong tac khen thurong ya ky
Please for non when of recipe chown qty cla invoing be inoc summary
Inual inamn pro ho chi minn,


# Summaries

In [10]:
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainingArguments,
    Seq2SeqTrainer,
    EarlyStoppingCallback,
)
import torch

from peft import LoraConfig, get_peft_model, TaskType, PeftModel

In [ ]:
# ==== Cấu hình cơ bản ====
BASE_MODEL = "VietAI/vit5-base"
LORA_PATH = "./quickquiz/Models/ViT5_checkpoint_epochs4"

# Seed
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cpu


In [14]:
base_model = AutoModelForSeq2SeqLM.from_pretrained(BASE_MODEL)
model = PeftModel.from_pretrained(base_model, LORA_PATH)
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL, use_fast=True)
tokenizer.padding_side = "right"


In [26]:
def summarize_text(text):
    """
    Sử dụng model summaries để tóm tắt văn bản.
    Model: mT5, ViT5,...
    """
    inputs = tokenizer(
        f'Tóm tắt: {text}',
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    outputs = model.generate(
        **inputs,
        max_length=250,
        num_beams=5,
        early_stopping=True,
    )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

In [32]:
text = '''Docker là một nền tảng phần mềm giúp bạn building, deploying và running ứng dụng dễ dàng hơn bằng cách sử dụng các containers (trên nền tảng ảo hóa).
Docker đóng gói phần mềm thành các container tiêu chuẩn hóa, chứa đựng tất cả những thứ cần thiết để phần mềm hoạt động như thư viện, công cụ hệ thống, mã nguồn và thời gian chạy. Khi cần deploy app lên bất kỳ server nào, bạn chỉ cần run container của Docker thì app của bạn sẽ được khởi chạy ngay lập tức.

Khi sử dụng Docker, bạn có thể dễ dàng triển khai và mở rộng quy mô ứng dụng trong bất kỳ môi trường nào, đồng thời đảm bảo rằng mã nguồn của bạn sẽ luôn chạy được một cách ổn định.
Container là các gói phần mềm nhỏ gọn chứa tất cả các thành phần cần thiết của một ứng dụng như mã nguồn, thư viện, và các công cụ, giúp đảm bảo ứng dụng có thể chạy đồng nhất trên mọi môi trường.

Bằng cách đó, nhờ vào container, ứng dụng sẽ chạy trên mọi máy Linux khác bất kể mọi cài đặt tùy chỉnh mà máy có thể khác với máy được sử dụng để viết code.
'''
print(summarize_text(text))


Docker là một nền tảng phần mềm giúp bạn building, deploying và running ứng dụng dễ dàng hơn bằng cách sử dụng các container tiêu chuẩn hóa. 


# DeepSeek OCR

In [4]:
from transformers import AutoModel, AutoTokenizer
import torch
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0'
model_name = 'deepseek-ai/DeepSeek-OCR'

tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
model = AutoModel.from_pretrained(model_name,trust_remote_code=True, use_safetensors=True)
model = model.eval().cuda().to(torch.bfloat16)

# prompt = "<image>\nFree OCR. "
prompt = "<image>\n<|grounding|>Convert the document to markdown. "
image_file = 'doc1.png'
output_path = 'your/output/dir'

res = model.infer(tokenizer, prompt=prompt, image_file=image_file, output_path = output_path, base_size = 1024, image_size = 640, crop_mode=True, save_results = True, test_compress = True)

ImportError: cannot import name 'LlamaFlashAttention2' from 'transformers.models.llama.modeling_llama' (d:\Study\Projects\HK7\QuichQuiz\venv\Lib\site-packages\transformers\models\llama\modeling_llama.py)

# TrOCR prepare data

In [1]:
import os, unicodedata, shutil
from collections import Counter
from tqdm import tqdm
from PIL import Image

# Các thư mục rec/
SRC_FOLDERS = [
    r"D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\InkData_line_processed\rec",
    r"D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\vi_00\rec",
    r"D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\vi_01\rec",
    r"D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\meta\rec",
    r"D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\random\rec",
]

OUT_DIR = r"D:\Study\Projects\HK7\QuichQuiz\dataset"
OUT_IMG_DIR = os.path.join(OUT_DIR, "images")
OUT_LABEL_PATH = os.path.join(OUT_DIR, "labels.txt")

SUBDIR_IMAGES = "train"
LABEL_FILENAME = "rec_gt_train.txt"

os.makedirs(OUT_IMG_DIR, exist_ok=True)

def normalize(text):
    return unicodedata.normalize("NFC", text).strip()

def parse_label(line):
    # Label format:  train/abc.png text
    parts = line.strip().split(maxsplit=1)  # tách theo mọi whitespace: space, tab...
    if len(parts) < 2:
        return None, None
    return parts[0].strip(), parts[1].strip()

def subset_name(folder):
    return os.path.basename(os.path.dirname(folder))


In [2]:
subset_reports = []

for folder in SRC_FOLDERS:
    name = subset_name(folder)
    img_dir = os.path.join(folder, SUBDIR_IMAGES)
    label_file = os.path.join(folder, LABEL_FILENAME)

    print(f"\n🔎 CHECK DATASET: {name}")

    if not os.path.exists(img_dir) or not os.path.exists(label_file):
        print("⚠️ Thiếu thư mục ảnh hoặc file nhãn → bỏ qua")
        continue

    images = [f for f in os.listdir(img_dir) if f.lower().endswith(("png","jpg","jpeg"))]
    labels_raw = open(label_file, encoding="utf8", errors="ignore").read().splitlines()

    label_items, bad = [], 0
    for ln in labels_raw:
        fn, txt = parse_label(ln.strip())
        if not fn or not txt:
            bad += 1
        else:
            label_items.append((fn, normalize(txt)))

    img_set = set(images)
    label_set = {fn for fn, _ in label_items}

    missing_label = img_set - label_set
    missing_img   = label_set - img_set
    dups = [k for k,v in Counter(fn for fn,_ in label_items).items() if v > 1]

    print(f"📁 Ảnh: {len(images)} | 📝 Dòng nhãn: {len(labels_raw)} | ✅ Nhãn hợp lệ: {len(label_set)}")
    print(f"❌ Nhãn lỗi dòng: {bad}")
    print(f"⚠️ Ảnh thiếu nhãn: {len(missing_label)}")
    print(f"⚠️ Nhãn thiếu ảnh: {len(missing_img)}")
    print(f"♻️ File trùng trong nhãn: {len(dups)}")

    subset_reports.append({
        "name": name,
        "img_dir": img_dir,
        "label_items": label_items,
        "img_set": img_set,
        "label_set": label_set,
        "num_img": len(images)
    })



🔎 CHECK DATASET: InkData_line_processed
📁 Ảnh: 7282 | 📝 Dòng nhãn: 7282 | ✅ Nhãn hợp lệ: 7282
❌ Nhãn lỗi dòng: 0
⚠️ Ảnh thiếu nhãn: 7282
⚠️ Nhãn thiếu ảnh: 7282
♻️ File trùng trong nhãn: 0

🔎 CHECK DATASET: vi_00
📁 Ảnh: 100000 | 📝 Dòng nhãn: 100000 | ✅ Nhãn hợp lệ: 100000
❌ Nhãn lỗi dòng: 0
⚠️ Ảnh thiếu nhãn: 100000
⚠️ Nhãn thiếu ảnh: 100000
♻️ File trùng trong nhãn: 0

🔎 CHECK DATASET: vi_01
📁 Ảnh: 100000 | 📝 Dòng nhãn: 100000 | ✅ Nhãn hợp lệ: 100000
❌ Nhãn lỗi dòng: 0
⚠️ Ảnh thiếu nhãn: 100000
⚠️ Nhãn thiếu ảnh: 100000
♻️ File trùng trong nhãn: 0

🔎 CHECK DATASET: meta
📁 Ảnh: 144000 | 📝 Dòng nhãn: 144000 | ✅ Nhãn hợp lệ: 144000
❌ Nhãn lỗi dòng: 0
⚠️ Ảnh thiếu nhãn: 144000
⚠️ Nhãn thiếu ảnh: 144000
♻️ File trùng trong nhãn: 0

🔎 CHECK DATASET: random
📁 Ảnh: 50000 | 📝 Dòng nhãn: 50000 | ✅ Nhãn hợp lệ: 50000
❌ Nhãn lỗi dòng: 0
⚠️ Ảnh thiếu nhãn: 50000
⚠️ Nhãn thiếu ảnh: 50000
♻️ File trùng trong nhãn: 0


In [3]:
used = set()
total = 0

with open(OUT_LABEL_PATH, "w", encoding="utf8") as label_out:
    for r in subset_reports:
        print(f"\n📦 Gộp subset: {r['name']} ({r['num_img']} ảnh)")

        for fn, text in tqdm(r["label_items"], desc=f"Merging {r['name']}"):
            img_name = os.path.basename(fn.strip())  # lấy tên file cuối
            src = os.path.join(r["img_dir"], img_name)
            if not os.path.exists(src) or not text:
                print("❗FILE NOT FOUND:", src)
                continue

            if not os.path.exists(src) or not text:
                continue

            # tránh đè file
            out_name = img_name
            if out_name in used:
                out_name = f"{r['name']}__{img_name}"

            dst = os.path.join(OUT_IMG_DIR, out_name)
            shutil.copy(src, dst)

            label_out.write(f"images/{out_name}|{text}\n")
            used.add(out_name)
            total += 1

print(f"\n✅ DONE MERGING")
print(f"🖼️ Tổng ảnh đã gộp: {total}")
print(f"📄 labels.txt: {OUT_LABEL_PATH}")
print(f"📂 images/: {OUT_IMG_DIR}")



📦 Gộp subset: InkData_line_processed (7282 ảnh)


Merging InkData_line_processed:   0%|          | 0/7282 [00:00<?, ?it/s]

Merging InkData_line_processed: 100%|██████████| 7282/7282 [01:58<00:00, 61.50it/s]



📦 Gộp subset: vi_00 (100000 ảnh)


Merging vi_00: 100%|██████████| 100000/100000 [36:25<00:00, 45.75it/s]



📦 Gộp subset: vi_01 (100000 ảnh)


Merging vi_01: 100%|██████████| 100000/100000 [35:29<00:00, 46.96it/s]



📦 Gộp subset: meta (144000 ảnh)


Merging meta: 100%|██████████| 144000/144000 [26:38<00:00, 90.06it/s]



📦 Gộp subset: random (50000 ảnh)


Merging random: 100%|██████████| 50000/50000 [09:18<00:00, 89.54it/s]


✅ DONE MERGING
🖼️ Tổng ảnh đã gộp: 401282
📄 labels.txt: D:\Study\Projects\HK7\QuichQuiz\dataset\labels.txt
📂 images/: D:\Study\Projects\HK7\QuichQuiz\dataset\images


In [5]:
print("CHECK PATH:", img_dir)
print("Files:", os.listdir(img_dir)[:5])


CHECK PATH: D:\Study\Projects\HK7\QuichQuiz\archive\VietOCR-Paddle\random\rec\train
Files: ['00000000.jpg', '00000001.jpg', '00000002.jpg', '00000003.jpg', '00000004.jpg']


In [4]:
len(os.listdir(OUT_IMG_DIR))


401282

In [2]:
import os, random, shutil
from tqdm.notebook import tqdm

# ==== CONFIG ====
LABEL_FILE = "dataset/labels.txt"
IMAGE_FOLDER = "dataset"
OUT_DIR = "data"

TRAIN_RATIO, VAL_RATIO, TEST_RATIO = 0.7, 0.1, 0.2
# =================

print("🔍 Đọc file nhãn...")
with open(LABEL_FILE, "r", encoding="utf-8") as f:
    lines = f.readlines()

print(f"📄 Tổng số dòng trong labels.txt: {len(lines)}")

# Shuffle để tránh bias
random.shuffle(lines)

# Tính số mẫu
total = len(lines)
train_size = int(total * TRAIN_RATIO)
val_size = int(total * VAL_RATIO)

train_data   = lines[:train_size]
val_data     = lines[train_size:train_size + val_size]
test_data    = lines[train_size + val_size:]

print(f"\n📊 Chia dữ liệu:")
print(f" - Train: {len(train_data)}")
print(f" - Valid: {len(val_data)}")
print(f" - Test : {len(test_data)}")

# ===== Tạo thư mục =====
for split in ["train", "valid", "test"]:
    os.makedirs(f"{OUT_DIR}/{split}/images", exist_ok=True)

# ===== Ghi labels =====
print("\n📝 Lưu file labels...")
open(f"{OUT_DIR}/train/labels.txt", "w", encoding="utf-8").writelines(train_data)
open(f"{OUT_DIR}/valid/labels.txt", "w", encoding="utf-8").writelines(val_data)
open(f"{OUT_DIR}/test/labels.txt" , "w", encoding="utf-8").writelines(test_data)

# ===== Hàm copy ảnh =====
def copy_images(data, split_name):
    missing = 0
    print(f"\n📁 Copy ảnh → {split_name} ...")

    for line in tqdm(data):
        raw_name = line.split("|")[0].strip()

        # Chỉ lấy tên file, bỏ prefix "images/"
        img_name = os.path.basename(raw_name)

        # Đường dẫn gốc
        src = os.path.join(IMAGE_FOLDER, raw_name)
        
        # Tạo đúng đường dẫn đích
        dst = os.path.join(f"{OUT_DIR}/{split_name}/images", img_name)

        print(f"SRC: {src}  → DST: {dst}")

        # Kiểm tra file
        if not os.path.exists(src):
            missing += 1
            print(f"⚠️ Thiếu ảnh: {src}")
            continue

        shutil.copy(src, dst)

    print(f"✅ Done {split_name} — thiếu {missing} ảnh\n")



# ===== Copy ảnh =====
copy_images(train_data, "train")
copy_images(val_data, "valid")
copy_images(test_data, "test")

print("🎯 Hoàn tất tách dữ liệu!")


🔍 Đọc file nhãn...
📄 Tổng số dòng trong labels.txt: 401282

📊 Chia dữ liệu:
 - Train: 280897
 - Valid: 40128
 - Test : 80257

📝 Lưu file labels...

📁 Copy ảnh → train ...


  0%|          | 0/280897 [00:00<?, ?it/s]

SRC: dataset\images/124278.jpg  → DST: data/train/images\124278.jpg
SRC: dataset\images/meta__86723.jpg  → DST: data/train/images\meta__86723.jpg
SRC: dataset\images/vi_01__68333.jpg  → DST: data/train/images\vi_01__68333.jpg
SRC: dataset\images/104155.jpg  → DST: data/train/images\104155.jpg
SRC: dataset\images/vi_01__59273.jpg  → DST: data/train/images\vi_01__59273.jpg
SRC: dataset\images/vi_01__31186.jpg  → DST: data/train/images\vi_01__31186.jpg
SRC: dataset\images/vi_01__50910.jpg  → DST: data/train/images\vi_01__50910.jpg
SRC: dataset\images/meta__12970.jpg  → DST: data/train/images\meta__12970.jpg
SRC: dataset\images/meta__24874.jpg  → DST: data/train/images\meta__24874.jpg
SRC: dataset\images/20140603_0042_KQBDVN_tg_0_3.png  → DST: data/train/images\20140603_0042_KQBDVN_tg_0_3.png
SRC: dataset\images/38062.jpg  → DST: data/train/images\38062.jpg
SRC: dataset\images/20140603_0033_BCCTC_tg_0_4.png  → DST: data/train/images\20140603_0033_BCCTC_tg_0_4.png
SRC: dataset\images/112179

KeyboardInterrupt: 